import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:project_a/models/movie_preview.dart';
import 'package:project_a/models/tmdb_models/tmdb_movie_preview.dart';
import 'package:project_a/pages/movie_page.dart';
import 'package:project_a/pages/search_page.dart';
import 'package:project_a/service/tmdb_service.dart';
import 'package:project_a/widgets/custom_search_bar.dart';
import 'package:project_a/widgets/home_widgets/genres_section.dart';
import 'package:project_a/widgets/movie_card/movie_card.dart';

class HomePage extends StatelessWidget {
  final Function(int movieId) onMovieSelected;

  const HomePage({super.key, required this.onMovieSelected});

  final List<Map<String, dynamic>> xx = const [
    {
      "adult": false,
      "backdrop_path": "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      "genre_ids": [14, 10751, 28],
      "id": 1087192,
      "original_language": "en",
      "original_title": "How to Train Your Dragon",
      "overview":
          "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      "popularity": 904.7178,
      "poster_path": "/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg",
      "release_date": "2025-06-06",
      "title": "How to Train Your Dragon",
      "video": false,
      "vote_average": 8.091,
      "vote_count": 1216,
    },
    {
      "adult": false,
      "backdrop_path": "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
      "genre_ids": [28, 878, 53],
      "id": 1071585,
      "original_language": "en",
      "original_title": "M3GAN 2.0",
      "overview":
          "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
      "popularity": 608.4451,
      "poster_path": "/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
      "release_date": "2025-06-25",
      "title": "M3GAN 2.0",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 468,
    },
    {
      "adult": false,
      "backdrop_path": "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      "genre_ids": [16, 28, 14, 53],
      "id": 1311031,
      "original_language": "ja",
      "original_title": "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      "overview":
          "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
      "popularity": 508.5982,
      "poster_path": "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
      "release_date": "2025-07-18",
      "title": "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      "video": false,
      "vote_average": 6.827,
      "vote_count": 26,
    },
    {
      "adult": false,
      "backdrop_path": "/8or4S9BPhkeYK0vlKsPFee4JVWI.jpg",
      "genre_ids": [28, 18],
      "id": 1315986,
      "original_language": "en",
      "original_title": "Man with No Past",
      "overview":
          "Waking up in an unfamiliar city, a man with no memory must confront the mysteries of his own identity. However, his desperate search to uncover the past pits him against a powerful enemy, leading to a showdown that ultimately reveals the truth.",
      "popularity": 382.1417,
      "poster_path": "/eWHvROuznSzcxBAAkzX1X0Rmzoe.jpg",
      "release_date": "2025-01-13",
      "title": "Man with No Past",
      "video": false,
      "vote_average": 6.703,
      "vote_count": 32,
    },
    {
      "adult": false,
      "backdrop_path": "/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg",
      "genre_ids": [878, 12, 28],
      "id": 1061474,
      "original_language": "en",
      "original_title": "Superman",
      "overview":
          "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
      "popularity": 333.5035,
      "poster_path": "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
      "release_date": "2025-07-09",
      "title": "Superman",
      "video": false,
      "vote_average": 7.428,
      "vote_count": 1153,
    },
    {
      "adult": false,
      "backdrop_path": "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
      "genre_ids": [28, 12, 18],
      "id": 1011477,
      "original_language": "en",
      "original_title": "Karate Kid: Legends",
      "overview":
          "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      "popularity": 317.8487,
      "poster_path": "/AEgggzRr1vZCLY86MAp93li43z.jpg",
      "release_date": "2025-05-08",
      "title": "Karate Kid: Legends",
      "video": false,
      "vote_average": 7.229,
      "vote_count": 536,
    },
    {
      "adult": false,
      "backdrop_path": "/h6gChZHFpmbwqwV3uQsoakp77p1.jpg",
      "genre_ids": [28, 35],
      "id": 1124619,
      "original_language": "en",
      "original_title": "Bride Hard",
      "overview":
          "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
      "popularity": 315.3122,
      "poster_path": "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
      "release_date": "2025-06-19",
      "title": "Bride Hard",
      "video": false,
      "vote_average": 5.967,
      "vote_count": 30,
    },
    {
      "adult": false,
      "backdrop_path": "/962KXsr09uK8wrmUg9TjzmE7c4e.jpg",
      "genre_ids": [28, 53, 18],
      "id": 1119878,
      "original_language": "en",
      "original_title": "Ice Road: Vengeance",
      "overview":
          "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
      "popularity": 296.3004,
      "poster_path": "/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
      "release_date": "2025-06-27",
      "title": "Ice Road: Vengeance",
      "video": false,
      "vote_average": 6.965,
      "vote_count": 142,
    },
    {
      "adult": false,
      "backdrop_path": "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
      "genre_ids": [28, 53, 80],
      "id": 541671,
      "original_language": "en",
      "original_title": "Ballerina",
      "overview":
          "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
      "popularity": 252.489,
      "poster_path": "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
      "release_date": "2025-06-04",
      "title": "Ballerina",
      "video": false,
      "vote_average": 7.491,
      "vote_count": 1141,
    },
    {
      "adult": false,
      "backdrop_path": "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
      "genre_ids": [878, 12, 28],
      "id": 1234821,
      "original_language": "en",
      "original_title": "Jurassic World Rebirth",
      "overview":
          "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
      "popularity": 237.1881,
      "poster_path": "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
      "release_date": "2025-07-01",
      "title": "Jurassic World Rebirth",
      "video": false,
      "vote_average": 6.362,
      "vote_count": 793,
    },
    {
      "adult": false,
      "backdrop_path": "/xVcffNU61CclEGgtiWP7KLIE2dm.jpg",
      "genre_ids": [27, 28, 14, 12],
      "id": 1058537,
      "original_language": "en",
      "original_title": "Angels Fallen: Warriors of Peace",
      "overview":
          "When an Iraq War veteran receives a calling from a higher power, he embarks on a mission to stop a fallen angel from raising an army of the dead to take over the world.",
      "popularity": 235.2762,
      "poster_path": "/dKdKUSGQ9E0G73WPr9xIHrofpkT.jpg",
      "release_date": "2024-07-09",
      "title": "Angels Fallen: Warriors of Peace",
      "video": false,
      "vote_average": 5.62,
      "vote_count": 25,
    },
    {
      "adult": false,
      "backdrop_path": "/9l6bcHNFLR2fcCBSPzEeqxiQhwU.jpg",
      "genre_ids": [28, 35, 80, 9648],
      "id": 1374534,
      "original_language": "nl",
      "original_title": "Bad Boa's",
      "overview":
          "When an overeager community officer and a reckless ex-detective are forced to team up, plenty of chaos ensues on the streets of Rotterdam.",
      "popularity": 219.4051,
      "poster_path": "/7bcndiaTgu1Kj5a6qyCmsWYdtI.jpg",
      "release_date": "2025-07-10",
      "title": "Almost Cops",
      "video": false,
      "vote_average": 5.9,
      "vote_count": 96,
    },
    {
      "adult": false,
      "backdrop_path": "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
      "genre_ids": [16, 14, 35, 10402, 10751, 28],
      "id": 803796,
      "original_language": "en",
      "original_title": "KPop Demon Hunters",
      "overview":
          "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
      "popularity": 211.4319,
      "poster_path": "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
      "release_date": "2025-06-20",
      "title": "KPop Demon Hunters",
      "video": false,
      "vote_average": 8.519,
      "vote_count": 788,
    },
    {
      "adult": false,
      "backdrop_path": "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      "genre_ids": [28, 878, 12],
      "id": 986056,
      "original_language": "en",
      "original_title": "Thunderbolts*",
      "overview":
          "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
      "popularity": 201.3352,
      "poster_path": "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
      "release_date": "2025-04-30",
      "title": "Thunderbolts*",
      "video": false,
      "vote_average": 7.412,
      "vote_count": 1982,
    },
    {
      "adult": false,
      "backdrop_path": "/fd9K7ZDfzRAcbLh8JlG4HIKbtuR.jpg",
      "genre_ids": [28, 14],
      "id": 846422,
      "original_language": "en",
      "original_title": "The Old Guard 2",
      "overview":
          "Andy and her team of immortal warriors fight with renewed purpose as they face a powerful new foe threatening their mission to protect humanity.",
      "popularity": 167.3005,
      "poster_path": "/wqfu3bPLJaEWJVk3QOm0rKhxf1A.jpg",
      "release_date": "2025-07-01",
      "title": "The Old Guard 2",
      "video": false,
      "vote_average": 6,
      "vote_count": 544,
    },
    {
      "adult": false,
      "backdrop_path": "/vJbEUMeI2AxBUZKjP6ZVeVNNTLh.jpg",
      "genre_ids": [28, 53, 35],
      "id": 749170,
      "original_language": "en",
      "original_title": "Heads of State",
      "overview":
          "The UK Prime Minister and US President have a public rivalry that risks their countries' alliance. But when they become targets of a powerful enemy, they're forced to rely on each other as they go on a wild, multinational run. Allied with Noel, a brilliant MI6 agent, they must find a way to thwart a conspiracy that threatens the free world.",
      "popularity": 156.9191,
      "poster_path": "/lVgE5oLzf7ABmzyASEVcjYyHI41.jpg",
      "release_date": "2025-07-02",
      "title": "Heads of State",
      "video": false,
      "vote_average": 6.903,
      "vote_count": 549,
    },
    {
      "adult": false,
      "backdrop_path": "/lSbblLngbeZIn6G4WXDcyQ6SLhw.jpg",
      "genre_ids": [28, 18],
      "id": 911430,
      "original_language": "en",
      "original_title": "F1",
      "overview":
          "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
      "popularity": 144.233,
      "poster_path": "/9PXZIUsSDh4alB80jheWX4fhZmy.jpg",
      "release_date": "2025-06-25",
      "title": "F1",
      "video": false,
      "vote_average": 7.615,
      "vote_count": 893,
    },
    {
      "adult": false,
      "backdrop_path": "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      "genre_ids": [28, 12, 53, 80],
      "id": 7451,
      "original_language": "en",
      "original_title": "xXx",
      "overview":
          "Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government \"recruits\" him to go on a mission, he's not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.",
      "popularity": 140.0562,
      "poster_path": "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
      "release_date": "2002-08-09",
      "title": "xXx",
      "video": false,
      "vote_average": 6,
      "vote_count": 4481,
    },
    {
      "adult": false,
      "backdrop_path": "/iZ0ZSnhmHB3k1KDkDzEz65f5iia.jpg",
      "genre_ids": [16, 28, 878],
      "id": 1326106,
      "original_language": "ja",
      "original_title": "アニメ『怪獣８号』第１期総集編／同時上映「保科の休日」",
      "overview":
          "In a Kaiju-filled Japan, Kafka Hibino works in monster disposal. After reuniting with his childhood friend Mina Ashiro, a rising star in the anti-Kaiju Defense Force, he decides to pursue his abandoned dream of joining the Force, when he suddenly transforms into the powerful \"Kaiju No. 8.\" An action-packed recap of the first season of Kaiju No. 8 and a new original episode, Hoshina's Day Off.",
      "popularity": 130.2602,
      "poster_path": "/1aEfyTWUK8ZBk4aw7Ck0qEoF8PW.jpg",
      "release_date": "2025-03-28",
      "title": "Kaiju No. 8: Mission Recon",
      "video": false,
      "vote_average": 7.795,
      "vote_count": 39,
    },
    {
      "adult": false,
      "backdrop_path": "/tdMbbFhqyEqOK1QzNTvJjHWKbZX.jpg",
      "genre_ids": [27, 53, 28],
      "id": 1429744,
      "original_language": "th",
      "original_title": "ปากกัด ตีนถีบ",
      "overview":
          "In a fight for survival against a horrifying army of zombies, a former Muay Thai fighter must use skill, speed and grit to save his girlfriend.",
      "popularity": 110.17,
      "poster_path": "/yHYj2t3NzsjkHVYa0bPri4sMBsg.jpg",
      "release_date": "2025-07-09",
      "title": "Ziam",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 116,
    },
  ];

  final List<Map<String, dynamic>> comedyMovies = const [
    {
      "adult": false,
      "backdrop_path": "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
      "genre_ids": [10751, 878, 35, 12],
      "id": 552524,
      "original_language": "en",
      "original_title": "Lilo & Stitch",
      "overview":
          "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
      "popularity": 565.4793,
      "poster_path": "/c32TsWLES7kL1uy6fF03V67AIYX.jpg",
      "release_date": "2025-05-17",
      "title": "Lilo & Stitch",
      "video": false,
      "vote_average": 7.296,
      "vote_count": 1048,
    },
    {
      "adult": false,
      "backdrop_path": "/h6gChZHFpmbwqwV3uQsoakp77p1.jpg",
      "genre_ids": [28, 35],
      "id": 1124619,
      "original_language": "en",
      "original_title": "Bride Hard",
      "overview":
          "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
      "popularity": 315.3122,
      "poster_path": "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
      "release_date": "2025-06-19",
      "title": "Bride Hard",
      "video": false,
      "vote_average": 5.897,
      "vote_count": 29,
    },
    {
      "adult": false,
      "backdrop_path": "/9l6bcHNFLR2fcCBSPzEeqxiQhwU.jpg",
      "genre_ids": [28, 35, 80, 9648],
      "id": 1374534,
      "original_language": "nl",
      "original_title": "Bad Boa's",
      "overview":
          "When an overeager community officer and a reckless ex-detective are forced to team up, plenty of chaos ensues on the streets of Rotterdam.",
      "popularity": 219.4051,
      "poster_path": "/7bcndiaTgu1Kj5a6qyCmsWYdtI.jpg",
      "release_date": "2025-07-10",
      "title": "Almost Cops",
      "video": false,
      "vote_average": 5.9,
      "vote_count": 96,
    },
    {
      "adult": false,
      "backdrop_path": "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
      "genre_ids": [16, 14, 35, 10402, 10751, 28],
      "id": 803796,
      "original_language": "en",
      "original_title": "KPop Demon Hunters",
      "overview":
          "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
      "popularity": 211.4319,
      "poster_path": "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
      "release_date": "2025-06-20",
      "title": "KPop Demon Hunters",
      "video": false,
      "vote_average": 8.5,
      "vote_count": 786,
    },
    {
      "adult": false,
      "backdrop_path": "/vJbEUMeI2AxBUZKjP6ZVeVNNTLh.jpg",
      "genre_ids": [28, 53, 35],
      "id": 749170,
      "original_language": "en",
      "original_title": "Heads of State",
      "overview":
          "The UK Prime Minister and US President have a public rivalry that risks their countries' alliance. But when they become targets of a powerful enemy, they're forced to rely on each other as they go on a wild, multinational run. Allied with Noel, a brilliant MI6 agent, they must find a way to thwart a conspiracy that threatens the free world.",
      "popularity": 156.9191,
      "poster_path": "/lVgE5oLzf7ABmzyASEVcjYyHI41.jpg",
      "release_date": "2025-07-02",
      "title": "Heads of State",
      "video": false,
      "vote_average": 6.908,
      "vote_count": 547,
    },
    {
      "adult": false,
      "backdrop_path": "/wcFV4uOdSbC0cSjs7ecAyOU6t59.jpg",
      "genre_ids": [16, 10751, 12, 14, 35],
      "id": 947478,
      "original_language": "en",
      "original_title": "Diplodocus",
      "overview":
          "When the world around him is mysteriously erased, a little green dinosaur named Diplodocus must travel through the pages of a comic book and adventure through time to bring color back to his land. Alongside a wizard and two scientists, Diplo’s plans go awry as he learns that there may be a dimension to his world that he never considered.",
      "popularity": 116.2809,
      "poster_path": "/9mnMMiwv20EL5weJrLZCaF8cM2u.jpg",
      "release_date": "2024-10-04",
      "title": "The Green Dinosaur",
      "video": false,
      "vote_average": 8,
      "vote_count": 8,
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [35],
      "id": 968171,
      "original_language": "ja",
      "original_title": "性教育ママ",
      "overview":
          "An erotic comedy depicting the sex adventures of  young wives living in an apartment complex, that are not satisfied with just having sex with their husbands.",
      "popularity": 108.2958,
      "poster_path": "/xghWMg0pkBOdLHCTESyeyHU68wl.jpg",
      "release_date": "1973-11-20",
      "title": "Sex Education Mistresses",
      "video": false,
      "vote_average": 5.55,
      "vote_count": 10,
    },
    {
      "adult": false,
      "backdrop_path": "/cfAGn86j4LYzRCKWSkXPnMxoru6.jpg",
      "genre_ids": [18, 35],
      "id": 1406607,
      "original_language": "zh",
      "original_title": "戏台",
      "overview":
          "During the Republican era, wars and conflicts were frequent. On stage, the \"Overlord\" sings with resounding passion, while below, the absurd spectacle of life unfolds. They must both secure the opera troupe's livelihood and appease the audience in their seats. Once the curtain rises, how should this play be performed?",
      "popularity": 99.3657,
      "poster_path": "/wSFGtkoz8SW6yIgu1Xvxs584QQt.jpg",
      "release_date": "2025-07-12",
      "title": "The Stage",
      "video": false,
      "vote_average": 9.333,
      "vote_count": 3,
    },
    {
      "adult": false,
      "backdrop_path": "/9A0wQG38VdEu3DYh8HzXKXKhA6g.jpg",
      "genre_ids": [12, 35, 10751],
      "id": 1287536,
      "original_language": "en",
      "original_title": "Dora and the Search for Sol Dorado",
      "overview":
          "Dora, Diego, and their new friends trek through the perilous dangers of the Amazonian jungle in search of the ancient and powerful treasure of Sol Dorado to keep it out of enemy hands.",
      "popularity": 92.7851,
      "poster_path": "/r3d6u2n7iPoWNsSWwlJJWrDblOH.jpg",
      "release_date": "2025-07-02",
      "title": "Dora and the Search for Sol Dorado",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 71,
    },
    {
      "adult": false,
      "backdrop_path": "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
      "genre_ids": [14, 35, 10751, 12, 28],
      "id": 950387,
      "original_language": "en",
      "original_title": "A Minecraft Movie",
      "overview":
          "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
      "popularity": 81.7709,
      "poster_path": "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
      "release_date": "2025-03-31",
      "title": "A Minecraft Movie",
      "video": false,
      "vote_average": 6.443,
      "vote_count": 2109,
    },
    {
      "adult": false,
      "backdrop_path": "/vNUwK5P42m81uG57kKI1WxSZwIQ.jpg",
      "genre_ids": [35, 10749],
      "id": 1403735,
      "original_language": "te",
      "original_title": "లైలా",
      "overview":
          "Sonu Model, a renowned beautician from the old city, is forced to disguise himself as Laila, leading to a series of comedic, romantic, and action-packed events. Chaos ensues in this hilarious laugh riot",
      "popularity": 72.4312,
      "poster_path": "/l4gsNxFPGpzbq0D6QK1a8vO1lBz.jpg",
      "release_date": "2025-02-14",
      "title": "Laila",
      "video": false,
      "vote_average": 5.8,
      "vote_count": 5,
    },
    {
      "adult": false,
      "backdrop_path": "/zldvlkHlHKwrD3kNidMoSNN4Ir6.jpg",
      "genre_ids": [16, 35, 10751, 12],
      "id": 1100998,
      "original_language": "en",
      "original_title": "SuperKlaus",
      "overview":
          "Santa Claus's wish comes true when he accidentally bumps his head and starts believing he's SuperKlaus. With the help of Billie and Leo his elf-xecutive assistant, SuperKlaus will take on a toy-obsessed businessman to save Christmas.",
      "popularity": 70.3504,
      "poster_path": "/8sgc5TA8xsi4wpKrf7XrFKscujQ.jpg",
      "release_date": "2024-11-01",
      "title": "SuperKlaus",
      "video": false,
      "vote_average": 6,
      "vote_count": 5,
    },
    {
      "adult": false,
      "backdrop_path": "/xVoj3HrOsnjOyyhqRD9jt5kTPc4.jpg",
      "genre_ids": [878, 35, 28],
      "id": 605722,
      "original_language": "en",
      "original_title": "Long Distance",
      "overview":
          "After crash-landing on an alien planet, an asteroid miner must contend with the challenges of his new surroundings, while making his way across the harsh terrain to the only other survivor – a woman who is trapped in her escape pod.",
      "popularity": 69.1895,
      "poster_path": "/m5NKltgQqqyoWJNuK18IqEGRG7J.jpg",
      "release_date": "2024-07-12",
      "title": "Long Distance",
      "video": false,
      "vote_average": 6.362,
      "vote_count": 170,
    },
    {
      "adult": false,
      "backdrop_path": "/68TGPnvmZ21NBOoV5IUZ4fQDyvZ.jpg",
      "genre_ids": [10402, 12, 10749, 35, 10751],
      "id": 1243341,
      "original_language": "en",
      "original_title": "Z-O-M-B-I-E-S 4: Dawn of the Vampires",
      "overview":
          "A new adventure dawns for Zed and Addison when their summer road trip takes an unexpected detour, landing them in the middle of yet another monster rivalry: Daywalkers vs. Vampires. Tensions flare when Zed and Addison find themselves acting as camp counselors between the two opposing supernatural factions. With the help of Eliza and Willa, they must convince sworn enemies Nova and Victor to try to unite their warring worlds before an even greater threat endangers them all.",
      "popularity": 68.1958,
      "poster_path": "/6rGsqBxI4r1YkS9FuraovWi465w.jpg",
      "release_date": "2025-07-10",
      "title": "Z-O-M-B-I-E-S 4: Dawn of the Vampires",
      "video": false,
      "vote_average": 7.067,
      "vote_count": 82,
    },
    {
      "adult": false,
      "backdrop_path": "/rx7aw7NGnIuCYorPBWeNPrgOMAc.jpg",
      "genre_ids": [35],
      "id": 1294949,
      "original_language": "es",
      "original_title": "Mamá Reinventada",
      "overview":
          "Marina decides to take Patricia, her mother, to live with her, who believes that she should behave like the widow she is now. Living with Marina, he realizes that there are many things to do. Both find a new world to explore.",
      "popularity": 65.5325,
      "poster_path": "/9HOJUlJ0aZfLdsjgKIDjjc5FbUV.jpg",
      "release_date": "2025-05-08",
      "title": "Mamá Reinventada",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 14,
    },
    {
      "adult": false,
      "backdrop_path": "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg",
      "genre_ids": [16, 12, 10751, 35],
      "id": 1241982,
      "original_language": "en",
      "original_title": "Moana 2",
      "overview":
          "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      "popularity": 61.3886,
      "poster_path": "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
      "release_date": "2024-11-21",
      "title": "Moana 2",
      "video": false,
      "vote_average": 7.061,
      "vote_count": 2578,
    },
    {
      "adult": false,
      "backdrop_path": "/eA4S3tlpYfEA7LTo3GOwYWzUG4z.jpg",
      "genre_ids": [10751, 35, 12, 16],
      "id": 1084153,
      "original_language": "en",
      "original_title": "Sneaks",
      "overview":
          "Ty, a misguided, one-of-a-kind designer sneaker, doesn’t know life outside the comforts of his velvet-lined shoebox. After his sister is stolen by a shady collector, Ty must venture into New York City to find and rescue her. In his adventure, Ty meets a ragtag group of footwear friends from all walks of life who help him find the courage to step outside of his shoebox and find his sole-mate.",
      "popularity": 59.6813,
      "poster_path": "/3SipvmtH9VOyLmII9JLs34qFfil.jpg",
      "release_date": "2025-04-17",
      "title": "Sneaks",
      "video": false,
      "vote_average": 5.792,
      "vote_count": 24,
    },
    {
      "adult": false,
      "backdrop_path": "/jpcmibRElSNX4wyxzi4RKo8Xd5u.jpg",
      "genre_ids": [16, 35, 18, 10749],
      "id": 1354253,
      "original_language": "zh",
      "original_title": "爱上她的理由 番外 约定的未来",
      "overview":
          "Freshman Yuan Juntang applied to Minsong University in order to get closer to Zhu Zhu, whom he has had a crush on. At the university, he meets Li Shiya who used to be his idol, and takes a temporary absence from school.",
      "popularity": 55.4044,
      "poster_path": "/hvY6vP4mRu5NPe2x02ft7mXBeS5.jpg",
      "release_date": "2024-02-13",
      "title": "The Girl Downstairs Extra: Promised Future",
      "video": false,
      "vote_average": 10,
      "vote_count": 1,
    },
    {
      "adult": false,
      "backdrop_path": "/57on65zgbTjmiMJSqqKVZ3c355p.jpg",
      "genre_ids": [35, 18],
      "id": 1246310,
      "original_language": "en",
      "original_title": "Madea's Destination Wedding",
      "overview":
          "Madea packs her best floral dresses and a whole lot of chaos when the Simmons family heads to the Bahamas for her grandniece's whirlwind wedding.",
      "popularity": 48.9472,
      "poster_path": "/jwMwRucnAROgWo9WLLmIqzHmmzi.jpg",
      "release_date": "2025-07-10",
      "title": "Madea's Destination Wedding",
      "video": false,
      "vote_average": 5.815,
      "vote_count": 46,
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [878, 35, 18],
      "id": 1365103,
      "original_language": "en",
      "original_title": "Marriage Unplugged",
      "overview":
          "Unhappy in their marriage, Suzanna and Andrew buy a male sex robot called James, who consequently uncovers the deep fractures in their relationship.",
      "popularity": 45.7229,
      "poster_path": "/3H99Wl52sBPRqXZ3LJjgODOLfwX.jpg",
      "release_date": "2024-10-28",
      "title": "Marriage Unplugged",
      "video": false,
      "vote_average": 8.7,
      "vote_count": 3,
    },
  ];

  final List<Map<String, dynamic>> moviesJson = const [
    {
      "adult": false,
      "backdrop_path": "/m7vBHmPQSokvN4hMQDxdJBdqAtJ.jpg",
      "id": 1263256,
      "title": "Happy Gilmore 2",
      "original_title": "Happy Gilmore 2",
      "overview":
          "Happy Gilmore isn't done with golf — not by a long shot. Since his retirement after his first Tour Championship win, Gilmore returns to finance his daughter's ballet classes.",
      "poster_path": "/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [35],
      "popularity": 16.6788,
      "release_date": "2025-07-25",
      "video": false,
      "vote_average": 6.963,
      "vote_count": 40,
    },
    {
      "adult": false,
      "backdrop_path": "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
      "id": 617126,
      "title": "The Fantastic Four: First Steps",
      "original_title": "The Fantastic Four: First Steps",
      "overview":
          "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
      "poster_path": "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [878, 12],
      "popularity": 279.4076,
      "release_date": "2025-07-23",
      "video": false,
      "vote_average": 7.306,
      "vote_count": 291,
    },
    {
      "adult": false,
      "backdrop_path": "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
      "id": 552524,
      "title": "Lilo & Stitch",
      "original_title": "Lilo & Stitch",
      "overview":
          "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
      "poster_path": "/c32TsWLES7kL1uy6fF03V67AIYX.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [10751, 878, 35, 12],
      "popularity": 565.4793,
      "release_date": "2025-05-17",
      "video": false,
      "vote_average": 7.304,
      "vote_count": 1057,
    },
    {
      "adult": false,
      "backdrop_path": "/As7NuiDRM4EO7LlJn2u8JWWsABp.jpg",
      "id": 9614,
      "title": "Happy Gilmore",
      "original_title": "Happy Gilmore",
      "overview":
          "Failed hockey player-turned-golf whiz Happy Gilmore — whose unconventional approach and antics on the green courts the ire of rival Shooter McGavin — is determined to win a PGA tournament so he can save his granny's house with the prize money. Meanwhile, an attractive tour publicist tries to soften Happy's image.",
      "poster_path": "/4RnCeRzvI1xk5tuNWjpDKzSnJDk.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [35],
      "popularity": 18.9059,
      "release_date": "1996-02-16",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 2842,
    },
    {
      "adult": false,
      "backdrop_path": "/lCKRTbMKlXlwSydZpIqPu6hP0n0.jpg",
      "id": 1285728,
      "title": "A Normal Woman",
      "original_title": "A Normal Woman",
      "overview":
          "When an unidentified disease starts to upend her life, a socialite must unravel the mystery behind it — before her whole sense of self falls apart.",
      "poster_path": "/p8QqvttODrPYdJLjAUvcUsJtDTD.jpg",
      "media_type": "movie",
      "original_language": "id",
      "genre_ids": [18, 53, 27],
      "popularity": 42.5104,
      "release_date": "2025-07-23",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 5,
    },
    {
      "adult": false,
      "backdrop_path": "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      "id": 1087192,
      "title": "How to Train Your Dragon",
      "original_title": "How to Train Your Dragon",
      "overview":
          "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      "poster_path": "/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [14, 10751, 28],
      "popularity": 904.7178,
      "release_date": "2025-06-06",
      "video": false,
      "vote_average": 8.091,
      "vote_count": 1216,
    },
    {
      "adult": false,
      "backdrop_path": "/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg",
      "id": 1061474,
      "title": "Superman",
      "original_title": "Superman",
      "overview":
          "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
      "poster_path": "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [878, 12, 28],
      "popularity": 333.5035,
      "release_date": "2025-07-09",
      "video": false,
      "vote_average": 7.428,
      "vote_count": 1152,
    },
    {
      "adult": false,
      "backdrop_path": "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      "id": 986056,
      "title": "Thunderbolts*",
      "original_title": "Thunderbolts*",
      "overview":
          "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
      "poster_path": "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [28, 878, 12],
      "popularity": 201.3352,
      "release_date": "2025-04-30",
      "video": false,
      "vote_average": 7.412,
      "vote_count": 1982,
    },
    {
      "adult": false,
      "backdrop_path": "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      "id": 7451,
      "title": "xXx",
      "original_title": "xXx",
      "overview":
          "Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government \"recruits\" him to go on a mission, he's not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.",
      "poster_path": "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [28, 12, 53, 80],
      "popularity": 140.0562,
      "release_date": "2002-08-09",
      "video": false,
      "vote_average": 6,
      "vote_count": 4481,
    },
    {
      "adult": false,
      "backdrop_path": "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
      "id": 1136867,
      "title": "Materialists",
      "original_title": "Materialists",
      "overview":
          "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
      "poster_path": "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [10749, 18],
      "popularity": 119.6993,
      "release_date": "2025-06-12",
      "video": false,
      "vote_average": 6.804,
      "vote_count": 161,
    },
    {
      "adult": false,
      "backdrop_path": "/4NI6e5SjIRn7Gt5P361MAIDiGpi.jpg",
      "id": 1285965,
      "title": "Dangerous Animals",
      "original_title": "Dangerous Animals",
      "overview":
          "A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.",
      "poster_path": "/9tk3Si960hg4E49eMt81dS7Qe9Z.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [27, 53],
      "popularity": 107.0802,
      "release_date": "2025-06-05",
      "video": false,
      "vote_average": 6.644,
      "vote_count": 59,
    },
    {
      "adult": false,
      "backdrop_path": "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      "id": 1311031,
      "title": "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      "original_title": "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      "overview":
          "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
      "poster_path": "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
      "media_type": "movie",
      "original_language": "ja",
      "genre_ids": [16, 28, 14, 53],
      "popularity": 508.5982,
      "release_date": "2025-07-18",
      "video": false,
      "vote_average": 6.827,
      "vote_count": 26,
    },
    {
      "adult": false,
      "backdrop_path": "/jvpkBenB6hv19WWYVlaiow8zklq.jpg",
      "id": 1175942,
      "title": "The Bad Guys 2",
      "original_title": "The Bad Guys 2",
      "overview":
          "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
      "poster_path": "/iPYgLLhQ69vIvgDtGFtAln4TYtM.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [10751, 35, 80, 12, 16],
      "popularity": 29.8108,
      "release_date": "2025-07-24",
      "video": false,
      "vote_average": 9.3,
      "vote_count": 3,
    },
    {
      "adult": false,
      "backdrop_path": "/kj1lMKnOAzTOJFbNiOpGnqmONJ4.jpg",
      "id": 1241470,
      "title": "Osiris",
      "original_title": "Osiris",
      "overview":
          "Special Forces commandos on a mission are abducted mid-operation by a mysterious spacecraft. Upon waking aboard, they find themselves prey to a relentless alien race in a fight for survival.",
      "poster_path": "/y9XxUGW2kCRY9TknGiKVsWJZPi3.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [878, 28, 27],
      "popularity": 3.8049,
      "release_date": "2025-07-25",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 7,
    },
    {
      "adult": false,
      "backdrop_path": "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
      "id": 541671,
      "title": "Ballerina",
      "original_title": "Ballerina",
      "overview":
          "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
      "poster_path": "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [28, 53, 80],
      "popularity": 252.489,
      "release_date": "2025-06-04",
      "video": false,
      "vote_average": 7.491,
      "vote_count": 1141,
    },
    {
      "adult": false,
      "backdrop_path": "/lSbblLngbeZIn6G4WXDcyQ6SLhw.jpg",
      "id": 911430,
      "title": "F1",
      "original_title": "F1",
      "overview":
          "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
      "poster_path": "/9PXZIUsSDh4alB80jheWX4fhZmy.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [28, 18],
      "popularity": 144.233,
      "release_date": "2025-06-25",
      "video": false,
      "vote_average": 7.615,
      "vote_count": 893,
    },
    {
      "adult": false,
      "backdrop_path": "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
      "id": 1071585,
      "title": "M3GAN 2.0",
      "original_title": "M3GAN 2.0",
      "overview":
          "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
      "poster_path": "/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [28, 878, 53],
      "popularity": 608.4451,
      "release_date": "2025-06-25",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 468,
    },
    {
      "adult": false,
      "backdrop_path": "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
      "id": 1234821,
      "title": "Jurassic World Rebirth",
      "original_title": "Jurassic World Rebirth",
      "overview":
          "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
      "poster_path": "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [878, 12, 28],
      "popularity": 237.1881,
      "release_date": "2025-07-01",
      "video": false,
      "vote_average": 6.362,
      "vote_count": 793,
    },
    {
      "adult": false,
      "backdrop_path": "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
      "id": 1233413,
      "title": "Sinners",
      "original_title": "Sinners",
      "overview":
          "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
      "poster_path": "/4CkZl1LK6a5rXBqJB2ZP77h3N5i.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [27, 28, 53],
      "popularity": 69.0773,
      "release_date": "2025-04-16",
      "video": false,
      "vote_average": 7.569,
      "vote_count": 2125,
    },
    {
      "adult": false,
      "backdrop_path": "/jRlarlInv5MQovi3dJLSxsQGBdW.jpg",
      "id": 1515139,
      "title": "Back to the Beginning: Ozzy's Final Bow",
      "original_title": "Back to the Beginning: Ozzy's Final Bow",
      "overview":
          "A powerful return to roots, this concert captures Black Sabbath in peak form - reuniting to deliver classic hits with raw energy and legendary precision. Filmed live, to be theatrically released in 2026.",
      "poster_path": "/iO8vwdtmOivoyUguheJtDLXp2Gq.jpg",
      "media_type": "movie",
      "original_language": "en",
      "genre_ids": [10402, 99],
      "popularity": 4.5567,
      "release_date": "2025-07-05",
      "video": false,
      "vote_average": 0,
      "vote_count": 0,
    },
  ];

  @override
  Widget build(BuildContext context) {
    List<MoviePreview> movies = moviesJson
        .map((json) => TmdbMoviePreview.fromJson(json))
        .toList();

    List<MoviePreview> comedy = comedyMovies
        .map((json) => TmdbMoviePreview.fromJson(json))
        .toList();

    List<MoviePreview> xxx = xx
        .map((json) => TmdbMoviePreview.fromJson(json))
        .toList();

    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: EdgeInsets.all(16),
          child: ListView(
            scrollDirection: Axis.vertical,
            children: [
              InkWell(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => SearchPage()),
                  );
                },
                child: CustomSearchBar(
                  onSearch: (value) {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => SearchPage(searchValue: value),
                      ),
                    );
                  },
                  focusNode: FocusNode(),
                ),
              ),
              GenresSection(),
              SizedBox(height: 16),

              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                spacing: 8,
                children: [
                  Text(
                    "Recentes",
                    style: GoogleFonts.montserrat(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 18,
                    ),
                  ),
                  SizedBox(
                    height: 160,
                    child: ListView(
                      scrollDirection: Axis.horizontal,
                      children: List.generate(movies.length, (index) {
                        return Padding(
                          padding: EdgeInsets.only(right: 8),
                          child: MovieCard(
                            details: movies[index],
                            enableDetailsSheet: true,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => MoviePage(
                                    movieId: movies[index].id,
                                    onBackToMain: () => {
                                      Navigator.pop(context),
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                        );
                      }),
                    ),
                  ),
                ],
              ),

              SizedBox(height: 8),

              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                spacing: 8,
                children: [
                  Text(
                    "Comedy",
                    style: GoogleFonts.montserrat(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 18,
                    ),
                  ),
                  SizedBox(
                    height: 160,
                    child: ListView(
                      scrollDirection: Axis.horizontal,
                      children: List.generate(comedy.length, (index) {
                        return Padding(
                          padding: EdgeInsets.only(right: 8),
                          child: MovieCard(
                            details: comedy[index],
                            enableDetailsSheet: true,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => MoviePage(
                                    movieId: movies[index].id,

                                    onBackToMain: () => {
                                      Navigator.pop(context),
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                        );
                      }),
                    ),
                  ),
                ],
              ),

              SizedBox(height: 8),

              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                spacing: 8,
                children: [
                  Text(
                    "Action",
                    style: GoogleFonts.montserrat(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 18,
                    ),
                  ),
                  SizedBox(
                    height: 160,
                    child: ListView(
                      scrollDirection: Axis.horizontal,
                      children: List.generate(xxx.length, (index) {
                        return Padding(
                          padding: EdgeInsets.only(right: 8),
                          child: MovieCard(
                            details: xxx[index],
                            enableDetailsSheet: true,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => MoviePage(
                                    movieId: movies[index].id,
                                    onBackToMain: () => {
                                      Navigator.pop(context),
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                        );
                      }),
                    ),
                  ),
                ],
              ),

              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                spacing: 8,
                children: [
                  Text(
                    "Terror",
                    style: GoogleFonts.montserrat(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 18,
                    ),
                  ),
                  SizedBox(
                    height: 160,
                    child: ListView(
                      scrollDirection: Axis.horizontal,
                      children: List.generate(comedy.length, (index) {
                        return Padding(
                          padding: EdgeInsets.only(right: 8),
                          child: MovieCard(
                            details: comedy[index],
                            enableDetailsSheet: true,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => MoviePage(
                                    movieId: movies[index].id,
                                    onBackToMain: () => {
                                      Navigator.pop(context),
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                        );
                      }),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
