final mockup = [
  {
    "adult": false,
    "backdrop_path": "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
    "genre_ids": [],
    "id": 1311550,
    "original_language": "en",
    "original_title": "House of Ga'a",
    "overview":
        "No auge do império Oyo, o feroz Bashorun Ga'a tornou-se mais poderoso que os reis que ele mesmo coroou, mas foi derrubado por seu próprio sangue.",
    "popularity": 5.3657,
    "poster_path": "/jtDAIoVst9Bj1VRcQKY2fj52VYe.jpg",
    "release_date": "2024-07-26",
    "title": "Casa de Ga'a",
    "video": false,
    "vote_average": 5.5,
    "vote_count": 117,
  },
  {
    "adult": false,
    "backdrop_path": "/51zEsrnLuMnTYjvM0xI2cmk2rxh.jpg",
    "genre_ids": [18, 10402],
    "id": 461191,
    "original_language": "en",
    "original_title": "A",
    "overview":
        "A young alcoholic ambient musician locks himself in his apartment on a dangerous seven day bender as he attempts to finish his upcoming album.",
    "popularity": 0.6413,
    "poster_path": "/4uOKZzRB615cIxcVi31pcsdFtSS.jpg",
    "release_date": "2017-09-13",
    "title": "A",
    "video": false,
    "vote_average": 6.18,
    "vote_count": 203,
  },
  {
    "adult": false,
    "backdrop_path": null,
    "genre_ids": [],
    "id": 1286889,
    "original_language": "en",
    "original_title": "A",
    "overview":
        "In a close-knit community, imagine a teenager’s struggle with asexuality, where faith clashes with personal discovery.",
    "popularity": 0.4607,
    "poster_path": "/lv9a4uVBysAVqfKSZRYIdco2liL.jpg",
    "release_date": "2024-05-15",
    "title": "A",
    "video": false,
    "vote_average": 5.918,
    "vote_count": 55,
  },
];
