CREATE TABLE movies (
   id SERIAL PRIMARY KEY,
   title VARCHAR(255),
   original_title VARCHAR(255),
   tmdb_id INT,
   imdb_id VARCHAR(16) UNIQUE,
   original_language VARCHAR(255),
   release_date DATE,
   runtime INT,
   adult BOOLEAN,
   budget BIGINT,
   revenue BIGINT,
   popularity NUMERIC(10, 2),
   vote_average NUMERIC(5, 2),
   vote_count INT,
   overview TEXT,
   tagline TEXT,
   poster_path TEXT,
   backdrop_path TEXT,
   genres TEXT,
   production_companies TEXT,
   production_countries TEXT,
   spoken_languages TEXT,
   keywords TEXT
);
