List<Map<String, dynamic>> placeholder_movies_action = [
  {
    "adult": false,
    "backdrop_path": "/8J6UlIFcU7eZfq9iCLbgc8Auklg.jpg",
    "genre_ids": [14, 10751, 28],
    "id": 1087192,
    "original_language": "en",
    "original_title": "How to Train Your Dragon",
    "overview":
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    "popularity": 719.5787,
    "poster_path": "/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg",
    "release_date": "2025-06-06",
    "title": "How to Train Your Dragon",
    "video": false,
    "vote_average": 8.075,
    "vote_count": 1314,
  },
  {
    "adult": false,
    "backdrop_path": "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    "genre_ids": [16, 28, 14, 53],
    "id": 1311031,
    "original_language": "ja",
    "original_title": "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    "overview":
        "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
    "popularity": 637.777,
    "poster_path": "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
    "release_date": "2025-07-18",
    "title": "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 37,
  },
  {
    "adult": false,
    "backdrop_path": "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
    "genre_ids": [28, 878, 53],
    "id": 1071585,
    "original_language": "en",
    "original_title": "M3GAN 2.0",
    "overview":
        "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    "popularity": 456.3085,
    "poster_path": "/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
    "release_date": "2025-06-25",
    "title": "M3GAN 2.0",
    "video": false,
    "vote_average": 7.634,
    "vote_count": 534,
  },
  {
    "adult": false,
    "backdrop_path": "/h6gChZHFpmbwqwV3uQsoakp77p1.jpg",
    "genre_ids": [28, 35],
    "id": 1124619,
    "original_language": "en",
    "original_title": "Bride Hard",
    "overview":
        "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
    "popularity": 361.7358,
    "poster_path": "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
    "release_date": "2025-06-19",
    "title": "Bride Hard",
    "video": false,
    "vote_average": 5.9,
    "vote_count": 36,
  },
  {
    "adult": false,
    "backdrop_path": "/8or4S9BPhkeYK0vlKsPFee4JVWI.jpg",
    "genre_ids": [28, 18],
    "id": 1315986,
    "original_language": "en",
    "original_title": "Man with No Past",
    "overview":
        "Waking up in an unfamiliar city, a man with no memory must confront the mysteries of his own identity. However, his desperate search to uncover the past pits him against a powerful enemy, leading to a showdown that ultimately reveals the truth.",
    "popularity": 282.8766,
    "poster_path": "/eWHvROuznSzcxBAAkzX1X0Rmzoe.jpg",
    "release_date": "2025-01-13",
    "title": "Man with No Past",
    "video": false,
    "vote_average": 6.598,
    "vote_count": 41,
  },
  {
    "adult": false,
    "backdrop_path": "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
    "genre_ids": [28, 12, 18],
    "id": 1011477,
    "original_language": "en",
    "original_title": "Karate Kid: Legends",
    "overview":
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    "popularity": 278.5956,
    "poster_path": "/AEgggzRr1vZCLY86MAp93li43z.jpg",
    "release_date": "2025-05-08",
    "title": "Karate Kid: Legends",
    "video": false,
    "vote_average": 7.187,
    "vote_count": 565,
  },
  {
    "adult": false,
    "backdrop_path": "/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg",
    "genre_ids": [878, 12, 28],
    "id": 1061474,
    "original_language": "en",
    "original_title": "Superman",
    "overview":
        "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    "popularity": 292.5295,
    "poster_path": "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    "release_date": "2025-07-09",
    "title": "Superman",
    "video": false,
    "vote_average": 7.4,
    "vote_count": 1257,
  },
  {
    "adult": false,
    "backdrop_path": "/xVcffNU61CclEGgtiWP7KLIE2dm.jpg",
    "genre_ids": [27, 28, 14, 12],
    "id": 1058537,
    "original_language": "en",
    "original_title": "Angels Fallen: Warriors of Peace",
    "overview":
        "When an Iraq War veteran receives a calling from a higher power, he embarks on a mission to stop a fallen angel from raising an army of the dead to take over the world.",
    "popularity": 247.0547,
    "poster_path": "/dKdKUSGQ9E0G73WPr9xIHrofpkT.jpg",
    "release_date": "2024-07-09",
    "title": "Angels Fallen: Warriors of Peace",
    "video": false,
    "vote_average": 5.635,
    "vote_count": 37,
  },
  {
    "adult": false,
    "backdrop_path": "/962KXsr09uK8wrmUg9TjzmE7c4e.jpg",
    "genre_ids": [28, 53, 18],
    "id": 1119878,
    "original_language": "en",
    "original_title": "Ice Road: Vengeance",
    "overview":
        "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
    "popularity": 280.4298,
    "poster_path": "/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
    "release_date": "2025-06-27",
    "title": "Ice Road: Vengeance",
    "video": false,
    "vote_average": 6.902,
    "vote_count": 148,
  },
  {
    "adult": false,
    "backdrop_path": "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
    "genre_ids": [28, 53, 80],
    "id": 541671,
    "original_language": "en",
    "original_title": "Ballerina",
    "overview":
        "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    "popularity": 224.1039,
    "poster_path": "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
    "release_date": "2025-06-04",
    "title": "Ballerina",
    "video": false,
    "vote_average": 7.476,
    "vote_count": 1189,
  },
  {
    "adult": false,
    "backdrop_path": "/peAzdLKtT6VDWIfPQO9LJD1NCG4.jpg",
    "genre_ids": [878, 12, 28],
    "id": 1234821,
    "original_language": "en",
    "original_title": "Jurassic World Rebirth",
    "overview":
        "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    "popularity": 227.4073,
    "poster_path": "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    "release_date": "2025-07-01",
    "title": "Jurassic World Rebirth",
    "video": false,
    "vote_average": 6.343,
    "vote_count": 833,
  },
  {
    "adult": false,
    "backdrop_path": "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
    "genre_ids": [16, 14, 35, 10402, 10751, 28],
    "id": 803796,
    "original_language": "en",
    "original_title": "KPop Demon Hunters",
    "overview":
        "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
    "popularity": 188.8514,
    "poster_path": "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
    "release_date": "2025-06-20",
    "title": "KPop Demon Hunters",
    "video": false,
    "vote_average": 8.474,
    "vote_count": 841,
  },
  {
    "adult": false,
    "backdrop_path": "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
    "genre_ids": [28, 878, 12],
    "id": 986056,
    "original_language": "en",
    "original_title": "Thunderbolts*",
    "overview":
        "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
    "popularity": 206.1897,
    "poster_path": "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    "release_date": "2025-04-30",
    "title": "Thunderbolts*",
    "video": false,
    "vote_average": 7.413,
    "vote_count": 2049,
  },
  {
    "adult": false,
    "backdrop_path": "/9l6bcHNFLR2fcCBSPzEeqxiQhwU.jpg",
    "genre_ids": [28, 35, 80, 9648],
    "id": 1374534,
    "original_language": "nl",
    "original_title": "Bad Boa's",
    "overview":
        "When an overeager community officer and a reckless ex-detective are forced to team up, plenty of chaos ensues on the streets of Rotterdam.",
    "popularity": 188.9783,
    "poster_path": "/7bcndiaTgu1Kj5a6qyCmsWYdtI.jpg",
    "release_date": "2025-07-10",
    "title": "Almost Cops",
    "video": false,
    "vote_average": 5.84,
    "vote_count": 106,
  },
  {
    "adult": false,
    "backdrop_path": "/fd9K7ZDfzRAcbLh8JlG4HIKbtuR.jpg",
    "genre_ids": [28, 14],
    "id": 846422,
    "original_language": "en",
    "original_title": "The Old Guard 2",
    "overview":
        "Andy and her team of immortal warriors fight with renewed purpose as they face a powerful new foe threatening their mission to protect humanity.",
    "popularity": 148.3827,
    "poster_path": "/wqfu3bPLJaEWJVk3QOm0rKhxf1A.jpg",
    "release_date": "2025-07-01",
    "title": "The Old Guard 2",
    "video": false,
    "vote_average": 6.042,
    "vote_count": 571,
  },
  {
    "adult": false,
    "backdrop_path": "/vJbEUMeI2AxBUZKjP6ZVeVNNTLh.jpg",
    "genre_ids": [28, 53, 35],
    "id": 749170,
    "original_language": "en",
    "original_title": "Heads of State",
    "overview":
        "The UK Prime Minister and US President have a public rivalry that risks their countries' alliance. But when they become targets of a powerful enemy, they're forced to rely on each other as they go on a wild, multinational run. Allied with Noel, a brilliant MI6 agent, they must find a way to thwart a conspiracy that threatens the free world.",
    "popularity": 144.604,
    "poster_path": "/lVgE5oLzf7ABmzyASEVcjYyHI41.jpg",
    "release_date": "2025-07-02",
    "title": "Heads of State",
    "video": false,
    "vote_average": 7,
    "vote_count": 583,
  },
  {
    "adult": false,
    "backdrop_path": "/lSbblLngbeZIn6G4WXDcyQ6SLhw.jpg",
    "genre_ids": [28, 18],
    "id": 911430,
    "original_language": "en",
    "original_title": "F1",
    "overview":
        "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
    "popularity": 146.3497,
    "poster_path": "/6H6p82aWQFEKEuVUiZll6JxV8Ft.jpg",
    "release_date": "2025-06-25",
    "title": "F1",
    "video": false,
    "vote_average": 7.6,
    "vote_count": 926,
  },
  {
    "adult": false,
    "backdrop_path": "/a6bItEVaxgphpMswho1wVRerv4r.jpg",
    "genre_ids": [28, 12, 53, 80],
    "id": 7451,
    "original_language": "en",
    "original_title": "xXx",
    "overview":
        "Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government \"recruits\" him to go on a mission, he's not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.",
    "popularity": 139.1746,
    "poster_path": "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    "release_date": "2002-08-09",
    "title": "xXx",
    "video": false,
    "vote_average": 6,
    "vote_count": 4490,
  },
  {
    "adult": false,
    "backdrop_path": "/iZ0ZSnhmHB3k1KDkDzEz65f5iia.jpg",
    "genre_ids": [16, 28, 878],
    "id": 1326106,
    "original_language": "ja",
    "original_title": "アニメ『怪獣８号』第１期総集編／同時上映「保科の休日」",
    "overview":
        "In a Kaiju-filled Japan, Kafka Hibino works in monster disposal. After reuniting with his childhood friend Mina Ashiro, a rising star in the anti-Kaiju Defense Force, he decides to pursue his abandoned dream of joining the Force, when he suddenly transforms into the powerful \"Kaiju No. 8.\" An action-packed recap of the first season of Kaiju No. 8 and a new original episode, Hoshina's Day Off.",
    "popularity": 105.2211,
    "poster_path": "/1aEfyTWUK8ZBk4aw7Ck0qEoF8PW.jpg",
    "release_date": "2025-03-28",
    "title": "Kaiju No. 8: Mission Recon",
    "video": false,
    "vote_average": 7.767,
    "vote_count": 43,
  },
  {
    "adult": false,
    "backdrop_path": "/xPNDRM50a58uvv1il2GVZrtWjkZ.jpg",
    "genre_ids": [28, 12, 53],
    "id": 575265,
    "original_language": "en",
    "original_title": "Mission: Impossible - The Final Reckoning",
    "overview":
        "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
    "popularity": 90.7055,
    "poster_path": "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
    "release_date": "2025-05-17",
    "title": "Mission: Impossible - The Final Reckoning",
    "video": false,
    "vote_average": 7.165,
    "vote_count": 972,
  },
];
